### ISSUE TITLE
500 HTTP Internal Error

### ISSUE THREAD

**Issue by sxiii** [Adamant-im/adamant-android#4]
Cannot connect. Error is in the title. I can do a debug if you tell me where to look and what to do.

**Comment by PaulSeiziger** [comment]
Our new nodes fall when sending a request for normalization, at the moment the best thing you can do is switch to using old nodes (https://lake.adamant.im, https://endless.adamant.im, https:// clown.adamant.im). You can switch them in the list of nodes by double tap, or in the source code: helpers.Settings method getDefaultNodes

**Comment by PaulSeiziger** [comment]
Was my advice helpful? Can I close the issue?
